version: '2'

services:
  db: 
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=1234
    volumes:
        - ./mysql:/var/lib/mysql


  backend:
    image: golang:1.16.4
    volumes:
        - .:/go/src/code
    command: tail -F anything
    ports:
        - "9090:9090"